development: &default
  adapter: postgresql
  encoding: unicode
  database: tennis_book_development
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: tennis_book_test
  min_messages: warning
