#!/usr/bin/env sh

set -e

[[ ! $(which pg_config) ]] && brew install postgresql

[[ ! $(which bundler) ]] && gem install bundler

bundle

if [[ ! -e config/database.yml ]]; then
  cp config/database.yml{.example,}
fi

bundle exec rake db:create:all db:migrate db:setup db:seed
bundle exec rake db:test:prepare
bundle exec rake
